<?php

namespace App\Services\Attendance;

use App\Models\User;
use App\Models\Attendance;
use App\Models\AttendanceRule;
use Carbon\Carbon;

class AutoAttendanceService
{
    /**
     * Run auto attendance logic in chunks.
     */
    public function run(): void
    {
        $today = Carbon::today();
        $todayDate = $today->toDateString();
        $todayDay = strtolower($today->format('l'));

        User::chunkById(20, function ($users) use ($today, $todayDate, $todayDay) {
            foreach ($users as $user) {
                $this->processUser($user, $today, $todayDate, $todayDay);
            }
        });
    }

    /**
     * Process each user's attendance logic.
     */
    protected function processUser($user, $today, $todayDate, $todayDay): void
    {
        // Already marked today?
        $attendance = Attendance::where('user_id', $user->id)
            ->whereDate('created_at', $today)
            ->first();

        if ($attendance) return;

        // User rule or default rule
        $rule = AttendanceRule::where('user_id', $user->id)
            ->orWhereNull('user_id')
            ->orderByRaw('CASE WHEN user_id IS NULL THEN 2 ELSE 1 END')
            ->first();

        $status = 'Absent';

        if ($rule) {
            $weekends = $this->convertToArray($rule->weekend_holidays);
            $govHolidays = $this->convertToArray($rule->government_holidays);

            if (in_array($todayDay, array_map('strtolower', $weekends))) {
                $status = 'Weekend Holyday';
            } elseif (in_array($todayDate, $govHolidays)) {
                $status = 'Goverment Holyday';
            }
        }

        Attendance::create([
            'user_id' => $user->id,
            'check_in_time' => null,
            'check_out_time' => null,
            'status' => $status,
            'remarks' => 'Auto entry generated by system',
        ]);
    }

    /**
     * Convert JSON or comma string to array.
     */
    protected function convertToArray($value): array
    {
        if (!$value) return [];

        if ($this->isJson($value)) {
            return json_decode($value, true);
        }

        return array_map('trim', explode(',', $value));
    }

    protected function isJson($string): bool
    {
        json_decode($string);
        return (json_last_error() == JSON_ERROR_NONE);
    }
}
